### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by FanManutd** [TimofeySyrov/simpleSlider#8]
### Observer
Довольно странное использование Обсервера. С одной стороны, ты явно указываешь события модели, на которые можно подписаться, создавая по новому экземпляру обсервера на каждое событие. С другой стороны, сама модель может оповестить о каком-то событии и тут уже из кода тяжело догадаться, что это за событие. (ситуация с View аналогична)
![image](https://user-images.githubusercontent.com/90761929/150937816-cb176828-b060-4423-a4ea-de540d571b82.png)

Во первых сложнее догадаться, о чём же оповещают сами классы Model и View через this.notify. 
Во вторых у тебя на каждое событие создаётся экземпляр Обсервера. Если событий будет штук 10, то будет 10 экземпляров, что не есть хорошо. Как насчёт улучшить обсервер, что бы он мог принимать название события и коллбэк, который вызовется, когда это событие произойдёт. 

Более того, если я правильно понял, событие modelOptionsChanged существует для того, что бы его прослушивал сторонний код чуть ли не напрямую. Оно пробрасывается через цепочку геттеров. Во первых для этого существует API плагина, во вторых зачем? У тебя есть коллбэк onSlide, который вызывается когда пользователь взаимодействует со слайдером, пусть этот коллбэк вызывается с аргументом, который содержит текущее состояние слайдера. Его можно перенести в модель, что бы он вызывался после расчётов.

**Comment by TimofeySyrov** [comment]
В общем, я решил, раз выпал шанс попереписывать код, сразу обновить и опции слайдера. Мне не нравился интерфейс старых опций, особенно морока была с currentValue, который мог быть числом или объектом.

В кратце

* `currentValue` стал `from`, `to` опциями
* `type: "range"` стал `type: "single" | "double"` опцией.
* `type: "from-start" | "from-end"` стал `direction: "ltr" | "rtl"` опцией

Раньше `type: "range"` у меня использовался для включения второго ползунка. А значения "from-start" и "from-end" для положения слайдера. Решил разделить, отображение ползунков - `type` опция, положение слайдера -  `direction` опция.
